### ISSUE TITLE
How to use MFA via email at this point

### ISSUE THREAD

**Issue by danliu3458** [charlesjohannisen/auth0-mfa-flow#1]
Does this library support MFA via email at this point? and only enable email as an MFA factor?

**Comment by charlesjohannisen** [comment]
Not sure. I've only ever used sms. But try:
```javascript
const options = {
	challengeType: 'otp',
	authenticatorTypes: ['otp']
	grantType: 'http://auth0.com/oauth/grant-type/mfa-otp'
}
```
And make sure email is enabled in your account at /security/mfa

**Comment by danliu3458** [comment]
Hey Charles, thank you for your reply:)

There's one thing I couldn't find from docs. Please correct me if Im wrong. When Im trying logging in user using the code below, I expect err callback function will be called, but it doesn't work. 

```javascript
auth.login(
	{
		realm: 'Username-Password-Authentication',
		username: 'AUTH0_USER_USERNAME_FROM_USER_INPUT',
		password: 'AUTH0_USER_PASSWORD_FROM_USER_INPUT'
	},
	async (err, authResult) => {...
```

To make it work, I have to add `popup: true` or use auth.client.login to get rid of redirect based flow, otherwise I'll get the error in my call-back page. 

Is it true that this library only work for non-redirect flow, or it doesn't matter?  

```javascript
auth.login(
	{
		realm: 'Username-Password-Authentication',
		username: 'AUTH0_USER_USERNAME_FROM_USER_INPUT',
		password: 'AUTH0_USER_PASSWORD_FROM_USER_INPUT',
                popup: true
	},
	async (err, authResult) => {...
```

**Comment by danliu3458** [comment]
version used:     
"auth0-js": "^9.14.0",
"auth0-mfa-flow": "^1.0.4",

**Comment by charlesjohannisen** [comment]
The code should be background flow. I created this because I didn't want to use the auth0 pop-up or redirects. So, you should create your own login form and mfa code confirmation form. You shouldn't be redirected to or from an outside url.
Make sure your auth0 app is Single Page Application. Then at the bottom of the app settings at advanced setting, under grant types, select password and mfa.

**Comment by danliu3458** [comment]
Thanks, that's really good to know. I have proper settings as you mention

**Comment by danliu3458** [comment]
"auth.client.login" works for me, if I use "auth.login" instead will lead me to redirect flow which I'm trying to avoid

**Comment by charlesjohannisen** [comment]
Glad to be of some assistance. Will try to add a proper working example in the coming days for others who might want to try this out.
